In [2]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.io import loadmat

In [84]:
def shift_left(v):
    v[:,:-1] = v[:,1:]
    return v
    
def shift_right(v):
    v[:,1:] = v[:,:-1]
    return v

v = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
a = np.array([[2,3,3],
             [5,6,6],
             [8,9,9]])

b = np.array([[1,1,2],
             [4,4,5],
             [7,7,8]])

print(shift_left(v) + shift_right(v))
print(a+b)
# print(shift_left(v))
# print(shift_right(v))

[[ 4  4  6]
 [10 10 12]
 [16 16 18]]
[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]]


In [95]:
a = np.array([[1,2,3]]).T
b = np.array([[1,1,2,2,2,2]]).T
a[b]

array([[[2]],

       [[2]],

       [[3]],

       [[3]],

       [[3]],

       [[3]]])